import Head from 'next/head'

const About = () => {
  return (
    <>
      <Head>
        <title>A propos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="container">A propos</main>
    </>
  )
}
export default About
