import Head from 'next/head'

const Contact = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="content">
        <h1>Page Contact</h1>
      </main>
    </>
  )
}
export default Contact
