'use client'
import Head from 'next/head'
import styles from '@/src/pages/home/styles.module.css'
import Project from '@/src/components/Project/Index'
import HeaderPage from '@/src/components/headerPage'
import SocialNetwork from "@/src/components/socialNetwork"
import CursorHoverMask from "@/src/components/cursorHoverMask"

const Home: React.FC = () => {
    return (
    <>
      <Head>
        <title>UIX_DEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>
      <HeaderPage/>
      <main className={styles.main}>
        <SocialNetwork />
        <Project />
        <CursorHoverMask />
      </main>
    </>
  )
}

export default Home
