import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import HeaderImage from '@/public/images/uix_design_header.jpg'

export default function PortfolioSingle() {
  return (
    <>
      <Head>
        <title>Page portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="headerPage" >
        <div className="headerPage-text">
          <p>Bienvenu sur</p>
          <h1>
            UIX_DEV
          </h1>
        </div>
        <Image
          src={HeaderImage}
          alt="Qual-IT" 
          priority
        />
      </div>
      <h1>Portfolio with HEAD</h1>
    </>
  )
}
