import Head from 'next/head'
import { useEffect } from 'react'

export default function Portfolio() {

  return (
    <>
      <Head>
        <title>Page portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="content">
        <h1>Page portfolio</h1>
      </main>
    </>
  )
}
